### ISSUE TITLE
hardware backbutton troca o tema

### ISSUE THREAD

**Issue by JaoHundred** [JaoHundred/QRede#58]
Primeira execução do aplicativo:

### comportamento atual:

- trocado o tema claro para escuro
- fui até a coleção de qr codes
- apertei o hardware backbutton para voltar para a home
- estando na home apertei novamente para sair do app
- o app voltou para o tema claro

### esperado:

- trocado o tema claro para escuro
- fui até a coleção de qr codes
- apertei o hardware backbutton para voltar para a home
- estando na home apertei novamente para sair do app
- o app sai da aplicação sem trocar de tema

obs: isso só aconteceu na execução em que houve uma troca de tema, se o tema não é trocado nas execuções posteriores, esse erro não acontece

**Comment by xhugo92** [comment]
Apôs replicar os passos diversas vezes, não foi possível replicar o bug. Continuaremos observando nas futuras atualizações
